### ISSUE TITLE
Pretty-printed arrays not indented correctly

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#35] opened 2017-06-15 12:07 UTC
```csharp
var obj = JsonValue.Parse("[1,2]");
var writer = new JsonWriter(pretty: true) { IndentString = "  " };
writer.Serialize(obj);
```

Expected:

```
[
  1,
  2
]
```

Actual:

```
[
1  ,
2
]
```

:link: Originally found in DotNetAnalyzers/StyleCopAnalyzers#2406.

**Comment by MarcosLopezC** [comment] 2017-06-15 13:41
This is a duplicate of #25.

This issue was already fixed in commit d866746eaa58344dcc687ef86f8eeb6f80134b2e.

**Closed by MarcosLopezC** 2017-06-15 13:41 UTC
Labels: bug, duplicate
